version: '3.8'
services:
  app:
    build: .
    ports:
      - '80:3000'
    environment:
      NODE_ENV: production
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    restart: always
